const SET_COUNTRIES = "SET_COUNTRIES";
const SET_LOADING= "SET_LOADING";
const SET_ALERT = "SET_ALERT";
const REMOVE_ALERT = "REMOVE_ALERT"



export {
    SET_ALERT,
    SET_COUNTRIES,
    SET_LOADING,
    REMOVE_ALERT
}